In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib 
matplotlib.rcParams["figure.figsize"] = (20,10)


In [2]:
df1 = pd.read_csv("bengaluru_house_prices.csv")
df1.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [3]:
df2 = df1.drop(['area_type','society','balcony','availability','location'],axis='columns')

In [4]:
df2.isnull().sum()

size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [5]:
df3 = df2.dropna()
df3.isnull().sum()

size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [6]:
df3['bhk'] = df3['size'].apply(lambda x: int(x.split(' ')[0]))
df3.bhk.unique()

C:\Users\User\AppData\Local\Temp\ipykernel_14348\2716584372.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['bhk'] = df3['size'].apply(lambda x: int(x.split(' ')[0]))


array([ 2,  4,  3,  6,  1,  8,  7,  5, 11,  9, 27, 10, 19, 16, 43, 14, 12,
       13, 18], dtype=int64)

In [7]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [8]:
df3[~df3['total_sqft'].apply(is_float)].head(10)

size      total_sqft  bath    price  bhk
30       4 BHK     2100 - 2850   4.0  186.000    4
122      4 BHK     3067 - 8156   4.0  477.000    4
137      2 BHK     1042 - 1105   2.0   54.005    2
165      2 BHK     1145 - 1340   2.0   43.490    2
188      2 BHK     1015 - 1540   2.0   56.800    2
410      1 BHK  34.46Sq. Meter   1.0   18.500    1
549      2 BHK     1195 - 1440   2.0   63.770    2
648  9 Bedroom       4125Perch   9.0  265.000    9
661      2 BHK     1120 - 1145   2.0   48.130    2
672  4 Bedroom     3090 - 5002   4.0  445.000    4

In [9]:
def convert_sqft_to_num(x):
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0])+float(tokens[1]))/2
    try:
        return float(x)
    except:
        return None 

In [10]:
df4 = df3.copy()
df4.total_sqft = df4.total_sqft.apply(convert_sqft_to_num)
df4 = df4[df4.total_sqft.notnull()]
df4.head(2)

size  total_sqft  bath   price  bhk
0      2 BHK      1056.0   2.0   39.07    2
1  4 Bedroom      2600.0   5.0  120.00    4

In [11]:
df5 = df4.copy()
df5['price_per_sqft'] = df5['price']*100000/df5['total_sqft']
df5.head()

size  total_sqft  bath   price  bhk  price_per_sqft
0      2 BHK      1056.0   2.0   39.07    2     3699.810606
1  4 Bedroom      2600.0   5.0  120.00    4     4615.384615
2      3 BHK      1440.0   2.0   62.00    3     4305.555556
3      3 BHK      1521.0   3.0   95.00    3     6245.890861
4      2 BHK      1200.0   2.0   51.00    2     4250.000000

In [12]:
df5['price_total'] = df5['price']*100000
df5.head()

size  total_sqft  bath   price  bhk  price_per_sqft  price_total
0      2 BHK      1056.0   2.0   39.07    2     3699.810606    3907000.0
1  4 Bedroom      2600.0   5.0  120.00    4     4615.384615   12000000.0
2      3 BHK      1440.0   2.0   62.00    3     4305.555556    6200000.0
3      3 BHK      1521.0   3.0   95.00    3     6245.890861    9500000.0
4      2 BHK      1200.0   2.0   51.00    2     4250.000000    5100000.0

In [13]:
df5=df5.drop(['price'],axis='columns')
df5.head()

size  total_sqft  bath  bhk  price_per_sqft  price_total
0      2 BHK      1056.0   2.0    2     3699.810606    3907000.0
1  4 Bedroom      2600.0   5.0    4     4615.384615   12000000.0
2      3 BHK      1440.0   2.0    3     4305.555556    6200000.0
3      3 BHK      1521.0   3.0    3     6245.890861    9500000.0
4      2 BHK      1200.0   2.0    2     4250.000000    5100000.0

In [14]:
df5.to_csv("bhp.csv",index=False)

In [15]:
df5[df5.total_sqft/df5.bhk<300].head()

size  total_sqft  bath  bhk  price_per_sqft  price_total
9   6 Bedroom      1020.0   6.0    6    36274.509804   37000000.0
45  8 Bedroom       600.0   9.0    8    33333.333333   20000000.0
58  6 Bedroom      1407.0   4.0    6    10660.980810   15000000.0
68  8 Bedroom      1350.0   7.0    8     6296.296296    8500000.0
70  3 Bedroom       500.0   3.0    3    20000.000000   10000000.0

In [16]:
df6 = df5[~(df5.total_sqft/df5.bhk<300)]
df6.shape

(12457, 6)

In [18]:
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('bhk'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf[(subdf.price_per_sqft>(m-st)) & (subdf.price_per_sqft<=(m+st))]
        df_out = pd.concat([df_out,reduced_df],ignore_index=True)
    return df_out
df7 = remove_pps_outliers(df6)
df7.shape

(10551, 6)

In [19]:
df7[df7.bath>10]

size  total_sqft  bath  bhk  price_per_sqft  price_total
10534  9 Bedroom      3300.0  14.0    9    15151.515152   50000000.0
10545     10 BHK     12000.0  12.0   10     4375.000000   52500000.0
10546     10 BHK      4000.0  12.0   10     4000.000000   16000000.0

In [20]:
df9 = df7[df7.bath<df7.bhk+2]
df9.shape

(10433, 6)

In [21]:
df10 = df9.drop(['size','price_per_sqft'],axis='columns')
df10.head(3)

total_sqft  bath  bhk  price_total
0       600.0   1.0    1    1500000.0
1       510.0   1.0    1    2525000.0
2       600.0   1.0    1    3800000.0

In [22]:
X = df10.drop(['price_total'],axis='columns')
X.head(3)

total_sqft  bath  bhk
0       600.0   1.0    1
1       510.0   1.0    1
2       600.0   1.0    1

In [23]:
y = df10.price_total
y.head(3)

0    1500000.0
1    2525000.0
2    3800000.0
Name: price_total, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [25]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(X_train,y_train)
lr_clf.score(X_test,y_test)

0.7886191823604368

In [26]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

cross_val_score(LinearRegression(), X, y, cv=cv)

array([0.77873291, 0.43994676, 0.71564866, 0.73181376, 0.76128674])

In [33]:
lr_clf.predict([(1000,2,2)])

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4861919.60819228])

In [35]:
def predict_price(sqft,bath,bhk):    
    x = np.zeros(len(X.columns))
    x[0] = sqft
    x[1] = bath
    x[2] = bhk
   
    return lr_clf.predict([x])[0]

In [37]:
predict_price(500, 2, 2)

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


1494412.5563891064

In [38]:
import pickle
with open('banglore_home_prices_model.pickle','wb') as f:
    pickle.dump(lr_clf,f)

In [39]:
import json
columns = {
    'data_columns' : [col.lower() for col in X.columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))